# ./build/bin/erigon --config ./sepolia.config.yaml --chain=sepolia --verbosity>
# https://erigon.gitbook.io/erigon/advanced-usage/options
datadir : '~/erigon_sepolia_testnet'
internalcl : true
port : 30304
chain : "sepolia"
snapshots : false # for chain=sepolia, for mainnet=true
http: true
ws: true
http.addr: "127.0.0.1"
http.port: 8546
http.api : ["eth", "web3", "net", "debug", "trace", "txpool", "erigon"]
# https://github.com/ledgerwatch/erigon/blob/devel/cmd/downloader/readme.md
torrent.download.rate: 6mb
torrent.port: 42069
private.api.addr: "127.0.0.1:9091"
db.size.limit: '1TB'
