name: pnpm-workflow
on: [push]

jobs:
  pnpm-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    name: Build and test
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Monorepo install
        uses: ./.github/actions/pnpm-install

